config/routes.rb
Rails.application.routes.draw do
  # Root path of your application
  root 'recipes#index'

  # Devise routes for standard HTML interactions
  devise_for :users

  # Standard HTML routes for recipes, comments, categories, and profiles
  resources :recipes do
    resources :comments, only: [:create, :destroy]
  end

  resources :categories, only: [:index, :new, :create, :show]

  resource :profile, only: [:show, :edit, :update]

  # API routes under the namespace 'api/v1'
  namespace :api do
    namespace :v1 do
      # Devise routes for API, adjusting paths and pointing to specific controllers
      devise_for :users, controllers: {
        sessions: 'api/v1/sessions',
        registrations: 'api/v1/registrations'
      }, path: '', path_names: {
        sign_in: 'signin',
        sign_out: 'signout',
        registration: 'signup'  # Explicitly define the path name for user registration
      }, skip: [:omniauth_callbacks, :passwords, :confirmations, :unlocks]

      # API resource routes
      resources :recipes, controller: 'recipes' do
        resources :comments, only: [:create, :destroy], controller: 'comments'
      end
      resources :categories, only: [:index, :show], controller: 'categories'
      resource :profile, only: [:show, :update], controller: 'profiles'
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizations, dependent: :destroy
  has_many :recipes, through: :categorizations

  # Validation example
  validates :name, presence: true, uniqueness: true
end

app/controllers/api/v1/categories_controller.rb
module Api
  module V1
    class CategoriesController < ApiController
      def index
        categories = Category.all
        render json: categories
      end

      def show
        category = Category.find(params[:id])
        render json: category
      end
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show] # Assuming you want to show recipes by category
  before_action :authenticate_user!, except: [:index, :show] # Optional: Require authentication for creating categories

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def show
    # @recipes = @category.recipes # If you want to list recipes belonging to a category
    @category = Category.find(params[:id])
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_list.html.erb
<ul>
  <% Category.all.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% @categories.each do |category| %>
  <p>
    <%= link_to category.name, category_path(category) %>
  </p>
<% end %>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1><%= @category.name %> Recipes</h1>
<ul>
  <% @category.recipes.each do |recipe| %>
    <li><%= link_to recipe.title, recipe_path(recipe) %></li>
  <% end %>
</ul>